package br.ufal.ic.sheetCreator.decorator;

public enum Flag {
	PRIMEIRA, SEGUNDA, TERCEIRA, QUARTA, QUINTA, SEXTA, SETIMA, OITAVA, 
	CLASSICAL_TREBLE_CLEF,
	WHOLE_NOTE, HALF_NOTE, QUARTER_NOTE, EIGHTH_NOTE,
	C, D, E, F, G, A, B,
	SHARP, FLAT, NATURAL_SIGN,
	NONE,
	CLASSICAL_DOCUMENT,
}
