package br.ufal.ic.sheetCreator.decorator;

public enum Flag {
	PRIMEIRA, SEGUNDA, TERCEIRA, QUARTA, 
	CLASSICAL_TREBLE_CLEF,
	WHOLE_NOTE, HALF_NOTE, QUARTER_NOTE, EIGHTH_NOTE,
	C ,D, E, F, G, A, B,
	SHARP, FLAP, NATURAL_SIGN,
	NONE,
	CLASSICAL_DOCUMENT,
	FULL_DOC, FULL_STAFF, NO_FULL,
	NOT_CREATED, CHANGE_STAFF,
	STATE_0, STATE_1, STATE_2, STATE_3, STATE_4,
	FIM_DE_FITA, EMPTY, FORWARD
}
